-- CRIA VW_CONVENIO APENAS COM AS COLUNAS UTILIZADAS NO CONVENIO, SELECIONANDO APENAS CONVENIOS APROVADOS E REPROVADOS
USE siconv;
SET sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE TABLE tbl_convenio (NR_CONVENIO VARCHAR(20), ID_PROPOSTA VARCHAR(20), SIT_CONVENIO VARCHAR(255), QTD_TA INT, QTD_PRORROGA INT, MES INT, QTDE_CONVENIOS INT, VL_GLOBAL_CONV FLOAT, VL_REPASSE_CONV FLOAT, VL_CONTRAPARTIDA_CONV FLOAT, VL_DESEMBOLSADO_CONV FLOAT, DIA_INIC_VIGENC_CONV VARCHAR(20),DIA_FIM_VIGENC_CONV VARCHAR(20), DIA_FIM_VIGENC_ORIGINAL_CONV VARCHAR(20)) AS
  SELECT NR_CONVENIO, ID_PROPOSTA, SIT_CONVENIO, QTD_TA, QTD_PRORROGA, MES, QTDE_CONVENIOS, VL_GLOBAL_CONV, VL_REPASSE_CONV, VL_CONTRAPARTIDA_CONV, VL_DESEMBOLSADO_CONV, DIA_INIC_VIGENC_CONV, DIA_FIM_VIGENC_CONV, DIA_FIM_VIGENC_ORIGINAL_CONV
  FROM convenio;
  -- na carga do csv, selecionamos apenas os convenios validos
  -- WHERE SIT_CONVENIO IN ('Prestação de Contas Aprovada', 'Prestação de Contas Aprovada com Ressalvas', 'Inadimplente', 'Prestação de Contas Rejeitada', 'Convênio Rescindido');
  
CREATE INDEX idx_id_proposta ON tbl_convenio(id_proposta);

-- FAZ UM JOIN COM PROPSOTA, TRAZENDO AS COLUNAS DE INTERESSE, E JA CONSIDERANDO 'POSITIVO' (DE INTERESSE) A REPROVACAO
CREATE TABLE tbl_convenio_proposta (NR_CONVENIO VARCHAR(20), ID_PROPOSTA VARCHAR(20), SIT_CONVENIO VARCHAR(255), QTD_TA INT, QTD_PRORROGA INT, MES INT, QTDE_CONVENIOS INT, VL_GLOBAL_CONV FLOAT, VL_REPASSE_CONV FLOAT, VL_CONTRAPARTIDA_CONV FLOAT, VL_DESEMBOLSADO_CONV FLOAT, DIA_INIC_VIGENC_CONV VARCHAR(20),DIA_FIM_VIGENC_CONV VARCHAR(20), DIA_FIM_VIGENC_ORIGINAL_CONV VARCHAR(20), UF_PROPONENTE VARCHAR(10), COD_MUNIC_IBGE VARCHAR(255), COD_ORGAO_SUP VARCHAR(255), COD_ORGAO VARCHAR(255), MODALIDADE VARCHAR(255), IDENTIF_PROPONENTE VARCHAR(255), SITUACAO_CONTA VARCHAR(255), SITUACAO_PROJETO_BASICO VARCHAR(255), TARGET INT) AS
SELECT C.*, P.UF_PROPONENTE, P.COD_MUNIC_IBGE, P.COD_ORGAO_SUP, P.COD_ORGAO, P.MODALIDADE, P.IDENTIF_PROPONENTE, P.SITUACAO_CONTA, P.SITUACAO_PROJETO_BASICO,
CASE C.SIT_CONVENIO
	WHEN 'Prestação de Contas Aprovada' THEN 0
	WHEN 'Prestação de Contas Aprovada com Ressalvas' THEN 0
    WHEN 'Inadimplente' THEN 1
    WHEN 'Prestação de Contas Rejeitada' THEN 1
    WHEN 'Convênio Rescindido' THEN 1
END AS TARGET
FROM tbl_convenio C
LEFT JOIN proposta P ON C.ID_PROPOSTA = P.ID_PROPOSTA;

CREATE INDEX idx_id_proposta ON tbl_convenio_proposta(id_proposta);

-- CRIA TABELA JOIN COM EMENDA, COM QTDE DE EMENDAS POR CONVENIO
CREATE TABLE tbl_convenio_proposta_emenda (NR_CONVENIO VARCHAR(20), ID_PROPOSTA VARCHAR(20), SIT_CONVENIO VARCHAR(255), QTD_TA INT, QTD_PRORROGA INT, MES INT, QTDE_CONVENIOS INT, VL_GLOBAL_CONV FLOAT, VL_REPASSE_CONV FLOAT, VL_CONTRAPARTIDA_CONV FLOAT, VL_DESEMBOLSADO_CONV FLOAT, DIA_INIC_VIGENC_CONV VARCHAR(20),DIA_FIM_VIGENC_CONV VARCHAR(20), DIA_FIM_VIGENC_ORIGINAL_CONV VARCHAR(20), UF_PROPONENTE VARCHAR(10), COD_MUNIC_IBGE VARCHAR(255), COD_ORGAO_SUP VARCHAR(255), COD_ORGAO VARCHAR(255), MODALIDADE VARCHAR(255), IDENTIF_PROPONENTE VARCHAR(255), SITUACAO_CONTA VARCHAR(255), SITUACAO_PROJETO_BASICO VARCHAR(255), TARGET INT, EMENDAS INT) AS
SELECT C.*, COUNT(E.ID_PROPOSTA) AS EMENDAS
FROM tbl_convenio_proposta C
LEFT JOIN emenda E on C.ID_PROPOSTA = E.ID_PROPOSTA
GROUP BY C.NR_CONVENIO;

CREATE INDEX idx_nr_convenio ON tbl_convenio_proposta_emenda(NR_CONVENIO);
CREATE INDEX idx_id_proposta ON tbl_convenio_proposta_emenda(ID_PROPOSTA);

-- CRIA TABELA FINAL, JOIN COM CONSORCIO, TRAZENDO QTDE DE CNPJS COMPONENTES DE UM CONSORCIO
CREATE TABLE tbl_convenio_proposta_emenda_consorcio (NR_CONVENIO VARCHAR(20), ID_PROPOSTA VARCHAR(20), SIT_CONVENIO VARCHAR(255), QTD_TA INT, QTD_PRORROGA INT, MES INT, QTDE_CONVENIOS INT, VL_GLOBAL_CONV FLOAT, VL_REPASSE_CONV FLOAT, VL_CONTRAPARTIDA_CONV FLOAT, VL_DESEMBOLSADO_CONV FLOAT, DIA_INIC_VIGENC_CONV VARCHAR(20),DIA_FIM_VIGENC_CONV VARCHAR(20), DIA_FIM_VIGENC_ORIGINAL_CONV VARCHAR(20), UF_PROPONENTE VARCHAR(10), COD_MUNIC_IBGE VARCHAR(255), COD_ORGAO_SUP VARCHAR(255), COD_ORGAO VARCHAR(255), MODALIDADE VARCHAR(255), IDENTIF_PROPONENTE VARCHAR(255), SITUACAO_CONTA VARCHAR(255), SITUACAO_PROJETO_BASICO VARCHAR(255), TARGET INT, EMENDAS INT, CNPJS_CONSORCIOS INT) AS
SELECT C.*, COUNT(CON.ID_PROPOSTA) AS CNPJS_CONSORCIOS
FROM tbl_convenio_proposta_emenda C
LEFT JOIN (SELECT ID_PROPOSTA FROM consorcios GROUP BY CNPJ_PARTICIPANTE) CON ON C.ID_PROPOSTA = CON.ID_PROPOSTA
GROUP BY C.NR_CONVENIO;

CREATE INDEX idx_nr_convenio ON tbl_convenio_proposta_emenda_consorcio(NR_CONVENIO);
CREATE INDEX idx_id_proposta ON tbl_convenio_proposta_emenda_consorcio(ID_PROPOSTA);